apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - protocol: TCP
      name: odoo
      port: 8069
      targetPort: 8069