apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "pg-{{.Values.namespace}}"
provisioner: Local
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate