apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: postgresql-pvc
  namespace: {{.Values.namespace}}
spec:
  storageClassName: "pg-{{.Values.namespace}}"
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: {{.Values.postgres.storage}} # Sets volume size