apiVersion: v1
kind: Service
metadata:
  name: postgres-service 
  labels:
    app: postgres 
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres