apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{.Values.namespace}}
  labels:
    app: odoo
data:
  ODOO_EXTRA_MODULES: {{.Values.odoo.extramodules}}
  MAIN_GIT: {{.Values.odoo.mainrepo}}
  MAIN_BRANCH: {{.Values.odoo.mainbranch}}
  CUSTOM_GIT: {{.Values.odoo.customgit}}
  CUSTOM_GIT_BRANCH: {{.Values.odoo.customgitbranch}}