apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: ClusterIP
  ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
      name: web
    - port: 8072
      targetPort: 8072
      protocol: TCP
      name: longpolling
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: mailhog-web
  selector:
    app: odoo
